type User {
  _id: ID
  username: String! @unique
  email: String!
  password: String!
  avatar: String
  joinDate: String
  favorite: [Post]
}

type Post {
  title: String!
  imageUrl: String!
  categories: [String]!
  description: String
  createdDate: String
  likes: Int
  createdBy: User!
  message: [Message]
}

type Message {
  _id: ID
  messageBody: String!
  messageDate: String
  messageUser: User!
}
# Query is important, or else the apollo server will throw error.
type Query {
  getPost: [Post]
}

type Mutation {
  # adding a post mutation
  addPost(
    title: String!
    imageUrl: String!
    categories: [String]!
    description: String!
    creatorId: ID!
  ): Post!
  # this is a mutation for signup users
  signupUser(username: String!, email: String!, password: String!): User!
  signinUser(username: String!, password: String!): User!
}
